defaults:
  - shared
  - device: gpu
  - model: solaris
  - runner: inference
  - dataset@eval_datasets.eval_one_starts_away: eval_one_starts_away
  - dataset@eval_datasets.eval_same_direction: eval_same_direction
  - dataset@eval_datasets.eval_back_to_back: eval_back_to_back

  - _self_
